name: Build GBF Tool

on: [push]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Build with PyInstaller
        # We keep 'shell: bash' so we can use the "\" for clean multi-line code
        shell: bash
        run: |
          pyinstaller --noconsole --onefile \
          --add-data "db;db" \
          --add-data "style.qss;." \
          --name "GBF-Tool-Win.exe" main.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: GBF-Tool-Windows
          path: dist/GBF-Tool-Win.exe
